---
- hosts: webservers
  become: true
  tasks:
   - name: "Install httpd"
     yum:
       name: httpd
   - name: "know hostname"
     shell: "echo $HOSTNAME"
     register: print_hostname

   - name: "uptime"
     shell: echo -e "uptime:\t\t\t"`uptime | awk '{print $3,$4}' | sed 's/,//'`
     register: print_uptime

   - name: "Machine type"
     shell: echo -e "Machine Type:\t\t"`vserver=$(lscpu | grep Hypervisor | wc -l); if [ $vserver -gt 0 ]; then echo "VM"; else echo "Physical"; fi`
     register: print_machinetype

   - name: "memoria usada"
     shell: echo -e "Memory Usage:\t"`free | awk '/Mem/{printf("%.2f%"), $3/$2*100}'`
     register: print_memory
  
   - name: "Usuario Activo"
     shell: echo -e "Active User:\t\t"`w | cut -d ' ' -f1 | grep -v USER | xargs -n1`
     register: print_user

   - name: "CPU usada"
     shell: echo -e "CPU Usage:\t"`cat /proc/stat | awk '/cpu/{printf("%.2f%\n"), ($2+$4)*100/($2+$4+$5)}' |  awk '{print $0}' | head -1`
     register: print_cpu
  
   - name: "Configure httpd"
     template:
       src: templates/index.j2
       dest: /var/www/html/index.html
       owner: root
       group: wheel
       mode: '0644'
   - name: "Copy css"
     copy:
            src: templates/style.css
            dest: /home/vagrant
            owner: root
            group: wheel
            mode: '0644'
   - name: "start httpd"
     service:
      name: httpd
      state: restarted
      enabled: yes
